# Basic Information 
title: Yuqi Tang (唐宇祺)
position: Senior Undergraduate
affiliation: Zhejiang University
affiliation_link: https://www.zju.edu.cn/
affiliation_logo: ./assets/img/spinion.svg
email: yuqi.22 (at) intl.zju.edu.cn
email2: jamestt0396 (at) gmail.com
address: No. 718 Haizhou East Road, Haining, Zhejiang Province

# Search Engine Optimization (SEO)
keywords: yuqi tang, tang yuqi, yuqitang, tangyuqi
canonical: https://james-tyq.github.io/
description: Yuqi Tang is a final-year undergraduate student at Zhejiang University. His research lies at using Large Language Models (LLMs) to develop new concepts for AI for Science, AI for Engineering, and AI for Business.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?user=DJSQsXEAAAAJ&hl=en
github_link: https://github.com/James-TYQ
linkedin: https://www.linkedin.com/in/yuqi-tang-89b581334/
instagram: https://www.instagram.com/jamestt0396/

# Images 
avatar: ./assets/img/yuqi.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false
#footnote: Feel free to use my website's source code.
#footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: ${{ secrets.CLUSTRMAPS_ID }}

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: ${{ secrets.GOOGLE_SCHOLAR_ID }}

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one




# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
